version: '3.9'

services:
  usersegments:
    build: ./

    command: ./wait-for-postgres.sh db ./usersegments
    
    ports: 
      - 8080:8080
    container_name: usersegments
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
   

  db:

    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres   
    ports:
      - "5432:5432"
    volumes: 
      - ./.dbdata/postgres/data:/var/lib/postgresql/data